version: '3'
services:
  main:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: 'main'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres # user
      POSTGRES_PASSWORD: postgres # pass
    ports:
      - "5432:5432"
    volumes:
       - pgsql-data:/var/lib/postgresql/data
    container_name: db_postgres

volumes:
  pgsql-data:

